In [2]:
import numpy as np

# Attributes of ndarray

In [4]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a.dtype

dtype('int64')

### define data type like C struct
```
struct dt {
    string name;
    int age;
    float marks;
}
```

In [8]:
dt = np.dtype([('name', 'S20'), ('age', 'i1'), ('marks', 'f4')])
dt

dtype([('name', 'S20'), ('age', 'i1'), ('marks', '<f4')])

In [10]:
a = np.array([
    ('Jin', 25, 80),
    ('Tom', 3, 10)
], dtype=dt)
a

array([(b'Jin', 25, 80.), (b'Tom',  3, 10.)],
      dtype=[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')])

In [12]:
a.dtype

dtype([('name', 'S20'), ('age', 'i1'), ('marks', '<f4')])

### ndim, size, reshape, itemsize

In [14]:
a = np.arange(0, 10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
b = a.reshape((1, 2, 5))
b

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [18]:
a.ndim

1

In [20]:
b.ndim

3

In [22]:
a.shape

(10,)

In [24]:
b.shape

(1, 2, 5)

In [26]:
# bytes per item
a.itemsize

8

In [28]:
# memory infomation
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

# Create array

In [30]:
np.zeros((2, 3), dtype='int64')

array([[0, 0, 0],
       [0, 0, 0]])

In [32]:
np.ones((3, 2), dtype='float64')

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [34]:
# random initialize
np.empty((2, 2), dtype='int32')

array([[ 1262747648, -2117160148],
       [  331169688,  -536868865]], dtype=int32)

In [36]:
# convert python list to ndarray
x = [1, 2, 3]
np.asarray(x)

array([1, 2, 3])

In [38]:
def addOne(n=0):
    while True:
        yield n + 1
        n += 1

In [40]:
# Create from generator
np.fromiter(addOne(), dtype='int32', count=3)

array([1, 2, 3], dtype=int32)

In [42]:
a = np.linspace(0, 1)
a

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [44]:
# begin = 2^0, end = 2^9, 10 points
a = np.logspace(0, 9, 10, base=2)
a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

# Slice

In [46]:
a = np.arange(15).reshape((3, 5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
a[:, 4]

array([ 4,  9, 14])

In [50]:
a[1, :]

array([5, 6, 7, 8, 9])

In [52]:
a[0:2, 0:2]

array([[0, 1],
       [5, 6]])

In [54]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [56]:
# a[x_index, y_index]
b = a[[0, 0, 2, 2], [0, 4, 0, 4]]
b

array([ 0,  4, 10, 14])

In [58]:
a > 5

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [60]:
a[a % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [62]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [64]:
# swap row2 and row0
a[[2, 1, 0]]

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [66]:
# swap row2 and row0, then swap col2 and col0
a[np.ix_([2, 1, 0], [2, 1, 0, 3, 4])]

array([[12, 11, 10, 13, 14],
       [ 7,  6,  5,  8,  9],
       [ 2,  1,  0,  3,  4]])

In [68]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [70]:
a.shape

(3, 5)

In [72]:
b = np.arange(5)
b.shape

(5,)

In [74]:
b

array([0, 1, 2, 3, 4])

In [76]:
a + b

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18]])

In [78]:
b = np.arange(3)
b.shape

(3,)

In [80]:
a + b

ValueError: operands could not be broadcast together with shapes (3,5) (3,) 

In [98]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [99]:
for n in a:
    print(n)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]


In [81]:
for n in np.nditer(a, op_flags=['readwrite']):
    n[...] = n * 2

In [82]:
a

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [97]:
a = np.arange(24).reshape((2, 3, 4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [98]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [99]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [100]:
# b is reference of a
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [101]:
b[0] = 1000
a

array([[[1000,    1,    2,    3],
        [   4,    5,    6,    7],
        [   8,    9,   10,   11]],

       [[  12,   13,   14,   15],
        [  16,   17,   18,   19],
        [  20,   21,   22,   23]]])

In [103]:
a = np.arange(24).reshape((2, 3, 4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [109]:
b = a.transpose((2, 0, 1))
b.shape

(4, 2, 3)

In [112]:
# a[i][j][k] = b[k][i][j]
# b[i][j][k] = a[j][k][i]
b

array([[[ 0,  4,  8],
        [12, 16, 20]],

       [[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]]])

In [122]:
b = np.where(a==6)
b

(array([0]), array([1]), array([2]))

In [123]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [131]:
b = np.expand_dims(a, 1)
b.shape

(2, 1, 3, 4)

In [132]:
b

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]],


       [[[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]])

In [133]:
c = b.squeeze()
c.shape

(2, 3, 4)

In [137]:
b = np.expand_dims(b, 1)
b.shape

(2, 1, 1, 3, 4)

In [138]:
c = b.squeeze()
c.shape

(2, 3, 4)

In [153]:
a = np.arange(0, 6).reshape([3, 2])
b = np.arange(4, 8).reshape([2, 2])
print(f"a = {a}\n")
print(f"b = {b}\n")

a = [[0 1]
 [2 3]
 [4 5]]

b = [[4 5]
 [6 7]]



In [158]:
c = np.vstack((a, b))
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [4, 5],
       [6, 7]])

In [162]:
c = np.concatenate((a, b), axis=0)
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [4, 5],
       [6, 7]])

In [164]:
a = np.zeros(shape=(2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [168]:
b = np.unique(a)
print(b)

[0.]


In [170]:
a = np.array([
    [1, 2],
    [2, 3]
])
b = np.unique(a)
b

array([1, 2, 3])